spring:
  application:
    name: accounts

  datasource:
    url: ${DB_URI:jdbc:mysql://localhost:3307/accounts?createDatabaseIfNotExist=true}
    username: ${MYSQL_USER:account_user}
    password: ${MYSQL_PASSWORD:account123}
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true

server:
  port: ${PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

configuracao: 
  transactions: 
    service:
      url: ${TRANSACTIONS_URI:http://transactions}

logging:
  level:
    root: INFO

---

spring: 
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: 
