spring:
  application:
    name: transactions

  datasource:
    url: ${DB_URI:jdbc:mysql://localhost:3308/transactions?createDatabaseIfNotExist=true}
    username: ${MYSQL_USER:transaction_user}
    password: ${MYSQL_PASSWORD:transaction123}
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true

server:
  port: ${PORT:8082}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

configuracao: 
  accounts: 
    service:
      url: ${ACCOUNTS_URI:http://accounts}

logging:
  level:
    root: INFO

---

spring: 
  profiles: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: 
